import { stepenList, zwanieList } from '../../utils/Lists/List';

export const getInputsData = isMicrosoft => [
  {
    id: '0',
    name: t('form.name'),
    title: 'name',
    required: true,
    list: null,
    type: 'text',
    readOnly: isMicrosoft,
  },
  {
    id: '1',
    name: t('form.surname'),
    title: 'surname',
    required: true,
    list: null,
    type: 'text',
    readOnly: isMicrosoft,
  },
  {
    id: '2',
    name: t('form.patronymic'),
    title: 'patronymic',
    required: false,
    list: null,
    type: 'text',
    readOnly: isMicrosoft,
  },
  {
    id: '6',
    name: t('form.organization'),
    title: 'organization',
    required: true,
    list: null,
    type: 'text',
  },
  {
    id: '7',
    name: t('form.email'),
    title: 'email',
    required: true,
    list: null,
    type: 'email',
    disabled: true,
    readOnly: true,
  },
  {
    id: '8',
    name: t('form.phone'),
    title: 'phone',
    required: true,
    list: null,
    type: 'text',
  },
  {
    id: '3',
    name: t('form.academicTitle'),
    title: 'academicTitle',
    required: true,
    list: zwanieList,
    type: 'text',
  },
  {
    id: '4',
    name: t('form.degree'),
    title: 'degree',
    required: true,
    list: stepenList,
    type: 'text',
  },
  {
    id: '5',
    name: t('form.position'),
    title: 'position',
    required: false,
    list: null,
    type: 'text',
  },
];
