import { stepenList, zwanieList } from "../../utils/Lists/List";

export const inputsData = [
  {
    id: "0",
    name: "Ваше имя*",
    title: "name",
    required: true,
    list: null,
    type: "text",
  },
  {
    id: "1",
    name: "Ваша фамилия*",
    title: "surname",
    required: true,
    list: null,
    type: "text",
  },
  {
    id: "2",
    name: "Ваше отчество",
    title: "patronymic",
    required: false,
    list: null,
    type: "text",
  },
  {
    id: "3",
    name: "Ученое звание*",
    title: "academicTitle",
    required: true,
    list: zwanieList,
    type: "text",
  },
  {
    id: "4",
    name: "Степень*",
    title: "degree",
    required: true,
    list: stepenList,
    type: "text",
  },
  {
    id: "5",
    name: "Должность*",
    title: "position",
    required: true,
    list: null,
    type: "text",
  },
  {
    id: "6",
    name: "Организация*",
    title: "organization",
    required: true,
    list: null,
    type: "text",
  },
  {
    id: "7",
    name: "Email*",
    title: "email",
    required: true,
    list: null,
    type: "email",
    disabled: true,
  },
  {
    id: "8",
    name: "Номер*",
    title: "phone",
    required: true,
    list: null,
    type: "text",
  },
];
